<h1 align='center'> 파이썬과학프로그래밍기초 실습 7</h1>

<p style="text-align: right"> 2021.11.15.</p>

### <div class="alert alert-block alert-info">
    
- 파일 이름에서 00000000을 자신의 학번으로, name을 자신의 이름으로 수정하세요.

- 다음 줄에 자신의 이름, 학번, 학과(전공)을 적으세요.

* 이름:   김대성&nbsp;&nbsp;          학번:    20185212&nbsp;&nbsp;         학과(전공):    스마트IoT
    
</div>

- Jupyter notebook에 대한 설명은 [The Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/)을  참고하라

- Markdown은 [Markdown Guide](https://www.markdownguide.org/)를 참고하라.
- [Markdown Cheat Sheet](https://www.markdownguide.org/cheat-sheet/)

* 과제 제출: 11월 20일 (토) 오후 6:00까지 최종본 제출. 


#### 아래 셀에 다음 명령을 실행하라.

```
import numpy as np
np.__version__
```


In [3]:
import numpy as np
np.__version__

'1.19.2'

#### 예제 1.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)
```

In [4]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [5]:
a.dtype #int type

dtype('int64')

In [6]:
a = np.arange(8, dtype = np.int16)
a

array([0, 1, 2, 3, 4, 5, 6, 7], dtype=int16)

#### 예제 2.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 0,  2,  4,  6,  8, 10, 12, 14], dtype=int64)
```

In [10]:
np.arange(0, 15, 2, dtype = np.int64)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

#### 예제 3.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([1. , 1.2, 1.4, 1.6, 1.8])
```

In [11]:
np.arange(1, 1.9, 0.2)

array([1. , 1.2, 1.4, 1.6, 1.8])

#### 예제 4.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 0. ,  2.5,  5. ,  7.5, 10. ])
```

In [12]:
np.linspace(0, 10, 5) #sampling

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

#### 예제 5.
NumPy의 linspace를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [13]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 예제 6.
NumPy의 arange를 사용하여 다음 ndarray를 만들어라.

```
array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])
```

In [14]:
np.arange(1, 11, 2.25)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#### 예제 7.
NumPy의 arange와 reshape을 사용하여 다음 ndarray를 만들어라.

```
array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24], dtype=int64)
```

In [22]:
np.arange(2, 25, 2, dtype = np.int64).reshape(3, 4)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [23]:
np.arange(2, 25, 2, dtype = np.int64).reshape(3, 4).reshape(2, 6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [25]:
np.arange(2, 25, 2, dtype = np.int64).reshape(3, 2,2) # reshape(2,6)

array([[[ 2,  4],
        [ 6,  8]],

       [[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [26]:
np.arange(2, 25, 2, dtype = np.int64).reshape(2, 6)

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24]])

In [27]:
np.arange(2, 25, 2, dtype = np.int64).reshape(3, -1)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

### 리스트와 차이점

데이터 타입 지정가능 <br>
지정된 타입만 데이터로 사용가능

#### 예제 8.
예제 7에서 만든 ndarray에서 4, 12, 20의 합 36을 출력하는 문장 2 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [7]:
a = np.arange(2, 25, 2, dtype = np.int64).reshape(3, 4)
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [32]:
a.shape

(3, 4)

In [33]:
np.sum(a) #모든 원소 더함

156

In [34]:
np.sum(a, axis = 0) # 세로방향으로 더함

array([30, 36, 42, 48])

In [35]:
np.sum(a, axis = 1) # 가로방향으로 더함

array([20, 52, 84])

In [38]:
np.sum(a, axis = 0)[1]

36

In [41]:
np.sum(a, 0)[1]

36

In [49]:
a.sum(0)[1]

36

In [44]:
np.mean(a, axis = 1)

array([ 5., 13., 21.])

#### 예제 9.
예제 7에서 만든 ndarray에서 18, 20, 22, 24의 합 84를 출력하는 문장 3 개를 작성하라. (서로 다른 두 가지 방법으로 같은 결과를 출력하라)

In [9]:
np.sum(a, axis = 1)[2]

84

In [10]:
np.sum(a, 1)[2]

84

In [12]:
a.sum(1)[2]

84

#### 예제 10.
예제 7에서 만든 ndarray에서 2, 12, 22의 합 36을 출력하는 문장을 작성하라.

In [13]:
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [14]:
a.diagonal(0).sum()

36

In [15]:
np.diagonal(a)

array([ 2, 12, 22])

In [20]:
a[[0,1,2], [0,1,2]]

array([ 2, 12, 22])

#### 예제 11.
예제 7에서 만든 ndarray에서 4, 14, 24의 합 42을 출력하는 문장을 작성하라.

In [45]:
a

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [21]:
a.diagonal(1).sum()

42

#### 예제 12.
예제 7에서 만든 ndarray에서 10, 20의 합 30을 출력하는 문장을 작성하라.

In [33]:
a

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [23]:
a.diagonal(-1).sum()

30

#### 예제 13. 축 방향으로 함수 적용하기 
```
apply_along_axis(func1d, axis, arr, *args, **kwargs)
```


In [26]:
np.random.seed(1)
a = np.random.randint(1, 50, (3,5))
print(a)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]]


In [27]:
a.shape

(3, 5)

##### 13.1 축 방향으로 정렬하기

In [36]:
np.random.seed(1)
a = np.random.randint(1, 50, (3,5))
print(a)

[[38 44 13  9 10]
 [12  6 16  1 17]
 [ 2 13  8 46  7]]


In [32]:
a.shape

(3, 5)

In [33]:
a.sort()
a

array([[ 9, 10, 13, 38, 44],
       [ 1,  6, 12, 16, 17],
       [ 2,  7,  8, 13, 46]])

In [34]:
a.sort(-1)
a

array([[ 9, 10, 13, 38, 44],
       [ 1,  6, 12, 16, 17],
       [ 2,  7,  8, 13, 46]])

In [37]:
a.sort(1)
a

array([[ 9, 10, 13, 38, 44],
       [ 1,  6, 12, 16, 17],
       [ 2,  7,  8, 13, 46]])

##### 13.2 축 방향으로 사용자 정의 함수 적용하기

In [36]:
f = lambda x, y: x**y + 1
np.apply_along_axis(sorted, 0, a)

array([[ 1,  6,  8, 13, 17],
       [ 2,  7, 12, 16, 44],
       [ 9, 10, 13, 38, 46]])

In [38]:
f = lambda x, y: x**y + 1
np.apply_along_axis(f, 0, a, 2)

array([[  82,  101,  170, 1445, 1937],
       [   2,   37,  145,  257,  290],
       [   5,   50,   65,  170, 2117]])

In [39]:
a**2 + 1

array([[  82,  101,  170, 1445, 1937],
       [   2,   37,  145,  257,  290],
       [   5,   50,   65,  170, 2117]])

In [40]:
print(a)
min_a = np.apply_along_axis(min, 1, a)
print(a)
print(min_a)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]
[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]
[9 1 2]


In [41]:
np.min(a, 1)


array([9, 1, 2])

In [46]:
def is_odd(n):
    if n % 2:
        return True
    else:
        return False

In [47]:
is_odd(4)

False

In [34]:
@np.vectorize
def is_odd(n):
    if n % 2:
        return True
    else:
        return False

In [49]:
is_odd(4)

array(False)

In [38]:
print(a)
b = np.apply_along_axis(is_odd, 1, a)
print(a)
print(b)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]
[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]
[[ True False  True False False]
 [ True False False False  True]
 [False  True False  True False]]


In [39]:
c = np.apply_along_axis(is_odd, 0, a)
print(c)

[[ True False  True False False]
 [ True False False False  True]
 [False  True False  True False]]


In [43]:
def normalize(x): 
    return (x - x.min()) / (x.max() - x.min())

In [44]:
print(a)
np.apply_along_axis(normalize, 0, a)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]


array([[1.        , 1.        , 1.        , 1.        , 0.93103448],
       [0.        , 0.        , 0.8       , 0.12      , 0.        ],
       [0.125     , 0.25      , 0.        , 0.        , 1.        ]])

In [53]:
print(a)
np.apply_along_axis(normalize, 1, a)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]


array([[0.        , 0.02857143, 0.11428571, 0.82857143, 1.        ],
       [0.        , 0.3125    , 0.6875    , 0.9375    , 1.        ],
       [0.        , 0.11363636, 0.13636364, 0.25      , 1.        ]])

In [54]:
(a[0, :] + a[-1, :])*0.5

array([ 5.5,  8.5, 10.5, 25.5, 45. ])

In [55]:
np.argmax(a)

14

In [56]:
print(a)
np.argmax(a, 0)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]


array([0, 0, 0, 0, 2])

In [57]:
print(a)
np.argmax(a, 1)

[[ 9 10 13 38 44]
 [ 1  6 12 16 17]
 [ 2  7  8 13 46]]


array([4, 4, 4])

#### 예제 14. 
'fake_student_records.csv' 파일은 가상의 학생들의 시험 성적을 기록한 파일이다.
아래 프로그램은 이 파일의 한 줄을 딕셔너리로 변환하여 콘솔에 출력하는 프로그램이다.
```
import csv
with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    for row in csv_reader:
        print(row)
```
이 프로그램을 응용하여 학생들이 6 번 치룬 시험 결과를 2차원 numpy array로 변환한 후에 각 시험의 평균을 소숫점 첫째자리까지 콘솔에 출력하라.

정답은 다음과 같다.
```
[76.4 75.9 75.7 72.1 72.4 76.8]
```

In [53]:
import csv
with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    scores = []
    exams = ('시험1', '시험2', '시험3', '시험4', '시험5', '시험6')
    for row in csv_reader:
        scores.append([int(row[e]) for e in exams])
        print(row)

{'이름': '조준혁', '학번': '20257329', '소속': '일본학과', '학년': '3', '시험1': '61', '시험2': '69', '시험3': '46', '시험4': '79', '시험5': '57', '시험6': '77'}
{'이름': '이중석', '학번': '20287434', '소속': '심리학과', '학년': '2', '시험1': '83', '시험2': '55', '시험3': '76', '시험4': '62', '시험5': '62', '시험6': '64'}
{'이름': '정은영', '학번': '20297500', '소속': '경제학과', '학년': '2', '시험1': '57', '시험2': '61', '시험3': '61', '시험4': '72', '시험5': '98', '시험6': '84'}
{'이름': '조동욱', '학번': '20277510', '소속': '경제학과', '학년': '3', '시험1': '52', '시험2': '77', '시험3': '87', '시험4': '96', '시험5': '72', '시험6': '63'}
{'이름': '김승헌', '학번': '20317424', '소속': '경영학과', '학년': '3', '시험1': '83', '시험2': '90', '시험3': '93', '시험4': '71', '시험5': '89', '시험6': '92'}
{'이름': '정궁윤', '학번': '20299281', '소속': '생명과학과', '학년': '3', '시험1': '96', '시험2': '72', '시험3': '94', '시험4': '52', '시험5': '76', '시험6': '84'}
{'이름': '김민훈', '학번': '20317448', '소속': '의과학융합전공', '학년': '3', '시험1': '77', '시험2': '60', '시험3': '73', '시험4': '87', '시험5': '56', '시험6': '88'}
{'이름': '김동우', '학번': '20267372', '소속': '소프트웨어융합대학', 

In [54]:
scores

[[61, 69, 46, 79, 57, 77],
 [83, 55, 76, 62, 62, 64],
 [57, 61, 61, 72, 98, 84],
 [52, 77, 87, 96, 72, 63],
 [83, 90, 93, 71, 89, 92],
 [96, 72, 94, 52, 76, 84],
 [77, 60, 73, 87, 56, 88],
 [58, 47, 92, 61, 49, 70],
 [97, 82, 77, 58, 95, 55],
 [43, 67, 63, 90, 44, 85],
 [97, 84, 85, 54, 50, 97],
 [88, 58, 75, 65, 81, 61],
 [71, 99, 99, 59, 87, 97],
 [100, 74, 56, 57, 67, 63],
 [66, 93, 55, 81, 99, 88],
 [97, 97, 60, 92, 45, 91],
 [64, 71, 78, 82, 61, 99],
 [77, 57, 65, 59, 55, 74],
 [99, 60, 59, 50, 75, 89],
 [90, 76, 90, 87, 91, 72],
 [54, 74, 55, 99, 100, 89],
 [83, 87, 57, 85, 73, 65],
 [99, 64, 83, 77, 60, 93],
 [96, 96, 73, 78, 92, 99],
 [80, 93, 53, 73, 58, 72],
 [54, 61, 52, 65, 79, 69],
 [41, 86, 91, 78, 70, 60],
 [68, 99, 68, 74, 94, 44],
 [98, 87, 91, 51, 65, 62],
 [97, 62, 62, 61, 57, 72],
 [69, 60, 53, 68, 74, 79],
 [93, 96, 99, 64, 88, 59],
 [67, 89, 81, 80, 100, 78],
 [89, 71, 96, 63, 60, 89],
 [80, 65, 89, 88, 66, 70],
 [78, 83, 100, 69, 54, 56],
 [50, 63, 91, 72, 59, 99

In [55]:
scores = np.array(scores)
scores

array([[ 61,  69,  46,  79,  57,  77],
       [ 83,  55,  76,  62,  62,  64],
       [ 57,  61,  61,  72,  98,  84],
       [ 52,  77,  87,  96,  72,  63],
       [ 83,  90,  93,  71,  89,  92],
       [ 96,  72,  94,  52,  76,  84],
       [ 77,  60,  73,  87,  56,  88],
       [ 58,  47,  92,  61,  49,  70],
       [ 97,  82,  77,  58,  95,  55],
       [ 43,  67,  63,  90,  44,  85],
       [ 97,  84,  85,  54,  50,  97],
       [ 88,  58,  75,  65,  81,  61],
       [ 71,  99,  99,  59,  87,  97],
       [100,  74,  56,  57,  67,  63],
       [ 66,  93,  55,  81,  99,  88],
       [ 97,  97,  60,  92,  45,  91],
       [ 64,  71,  78,  82,  61,  99],
       [ 77,  57,  65,  59,  55,  74],
       [ 99,  60,  59,  50,  75,  89],
       [ 90,  76,  90,  87,  91,  72],
       [ 54,  74,  55,  99, 100,  89],
       [ 83,  87,  57,  85,  73,  65],
       [ 99,  64,  83,  77,  60,  93],
       [ 96,  96,  73,  78,  92,  99],
       [ 80,  93,  53,  73,  58,  72],
       [ 54,  61,  52,  6

In [57]:
scores.mean(0).round(1)

array([76.4, 75.9, 75.7, 72.1, 72.4, 76.8])

#### 문제 1.
다음 ndarray를 만들고 변수 a에 이 객체를 할당하라. 단, 모든 원소를 직접 나열하면 안된다.

```
array([[[  3   6   9  12  15]
       [ 18  21  24  27  30]
       [ 33  36  39  42  45]]

      [[ 48  51  54  57  60]
       [ 63  66  69  72  75]
       [ 78  81  84  87  90]]

      [[ 93  96  99 102 105]
       [108 111 114 117 120]
       [123 126 129 132 135]]

      [[138 141 144 147 150]
       [153 156 159 162 165]
       [168 171 174 177 180]]])
```

In [66]:
import numpy as np
b = np.arange(3,183,3)
a = b.reshape(4, 3, 5)
a

array([[[  3,   6,   9,  12,  15],
        [ 18,  21,  24,  27,  30],
        [ 33,  36,  39,  42,  45]],

       [[ 48,  51,  54,  57,  60],
        [ 63,  66,  69,  72,  75],
        [ 78,  81,  84,  87,  90]],

       [[ 93,  96,  99, 102, 105],
        [108, 111, 114, 117, 120],
        [123, 126, 129, 132, 135]],

       [[138, 141, 144, 147, 150],
        [153, 156, 159, 162, 165],
        [168, 171, 174, 177, 180]]])

#### 문제 2.
아래와 같이 a에 2 차원 배열이 할당되었다고 가정하자.
```
a = [[38 44 13  9 10]
     [12  6 16  1 17]
     [ 2 13  8 46  7]]
```
axis 0 방향으로 최대값에는 5를 더하고 최소값에는 5를 빼면 a는 다음과 같이 변한다.
```
a = [[43 49 13  9 10]
     [12  1 21 -4 22]
     [-3 13  3 51  2]]
```
이런 연산을 하는 프로그램을 만들어라. 단, apply_along_axis() 함수를 이용하라.

## 여러가지 테스트

In [95]:
import numpy as np
a = np.array([[38, 44, 13, 9, 10],
     [12, 6, 16, 1, 17],
     [2, 13, 8, 46, 7],])
a

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [83]:
x = np.apply_along_axis(lambda x: x, 0, a)
x

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [84]:
def f(b):
    print("실행!")
    print(b) #b : numpy형식 배열
    return b
x = np.apply_along_axis(f, 0, a)
x

실행!
[38 12  2]
실행!
[44  6 13]
실행!
[13 16  8]
실행!
[ 9  1 46]
실행!
[10 17  7]


array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [85]:
lst = [10, 20, 30]
print(lst)
lst[lst.index(max(lst))] += 5
lst[lst.index(min(lst))] -= 5
print(lst)

[10, 20, 30]
[5, 20, 35]


In [86]:
lst = np.array([10, 20, 30])
print(lst)
for i in range(len(lst)): # index() 사용불가
    if lst[i] == lst.max():
        lst[i] += 5
    elif lst[i] == lst.min():
        lst[i] -= 5
print(lst)

[10 20 30]
[ 5 20 35]


In [204]:
a = np.array([[38, 44, 13, 9, 10],
     [12, 6, 16, 1, 17],
     [2, 13, 8, 46, 7],])
a

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [205]:
def f(a):
    lst = a
    for i in range(len(lst)):
        if lst[i] == lst.max():
            lst[i] = lst[i] + 5
        elif lst[i] == lst.min():
            lst[i] = lst[i] - 5
    print(lst)
    return lst
    
x = np.apply_along_axis(f, 0, a)
x

[43 12 -3]
[49  1 13]
[13 21  3]
[ 9 -4 51]
[10 22  2]


array([[43, 49, 13,  9, 10],
       [12,  1, 21, -4, 22],
       [-3, 13,  3, 51,  2]])

In [209]:
a = np.array([[38, 44, 13, 9, 10],
     [12, 6, 16, 1, 17],
     [2, 13, 8, 46, 7],])
a

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

In [208]:
def max_add5_min_minus5(a):
    def f(lst):
        for i in range(len(lst)):
            if lst[i] == lst.max():
                lst[i] += 5
            elif lst[i] == lst.min():
                lst[i] -= 5
        return lst
    x = np.apply_along_axis(f, 0, a)
    return x

In [210]:
max_add5_min_minus5(a)

array([[43, 49, 13,  9, 10],
       [12,  1, 21, -4, 22],
       [-3, 13,  3, 51,  2]])

In [212]:
a = np.array([[38, 44, 13, 9, 10],
     [12, 6, 16, 1, 17],
     [2, 13, 8, 46, 7],])
a

array([[38, 44, 13,  9, 10],
       [12,  6, 16,  1, 17],
       [ 2, 13,  8, 46,  7]])

### 답

원본 array을 유지하고 새로운 numpy array로 반환

In [232]:
def max_add5_min_minus5(a):
    def f(lst):
        a = np.zeros(lst.shape, dtype = np.int64)
        for i in range(len(lst)):
            if lst[i] == lst.max():
                a[i] = lst[i] + 5
            elif lst[i] == lst.min():
                a[i] = lst[i] - 5
            else:
                a[i] = lst[i]
        return a
    x = np.apply_along_axis(f, 0, a)
    return x

In [233]:
max_add5_min_minus5(a)

array([[43, 49, 13,  9, 10],
       [12,  1, 21, -4, 22],
       [-3, 13,  3, 51,  2]])

## 테스트

In [117]:
np.apply_along_axis(lambda x: np.min(x)-5, 0, a)

array([-3,  1,  3, -4,  2])

In [118]:
np.apply_along_axis(lambda x: np.max(x)+5, 0, a)

array([43, 49, 21, 51, 22])

#### 문제 3.
예제 14에서 사용한 'fake_student_records.csv' 파일을 읽어서, 각 학생들의 6 번 시험 중에서 최저 점수를 제외한 5 번 시험의 평균을 구하여 소숫점 첫째 자리까지 콘솔에 출력하라. 정답은 다음과 같아야 한다.
```
array([68.6, 69.4, 75.2, 79. , 89.4, 84.4, 77. , 66. , 81.8, 69.8, 83.4,
       74. , 90.6, 72.2, 85.4, 87.4, 78.8, 66.4, 76.4, 86.8, 83.4, 78.6,
       83.2, 92.2, 75.2, 65.6, 77. , 80.6, 80.6, 70.8, 70. , 88. , 85.6,
       81.6, 78.6, 77.2, 76.8, 88.4])
```

In [266]:
import csv
with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    scores = []
    exams = ('시험1', '시험2', '시험3', '시험4', '시험5', '시험6')
    for row in csv_reader:
        scores.append([int(row[e]) for e in exams])
        print(row)

{'이름': '조준혁', '학번': '20257329', '소속': '일본학과', '학년': '3', '시험1': '61', '시험2': '69', '시험3': '46', '시험4': '79', '시험5': '57', '시험6': '77'}
{'이름': '이중석', '학번': '20287434', '소속': '심리학과', '학년': '2', '시험1': '83', '시험2': '55', '시험3': '76', '시험4': '62', '시험5': '62', '시험6': '64'}
{'이름': '정은영', '학번': '20297500', '소속': '경제학과', '학년': '2', '시험1': '57', '시험2': '61', '시험3': '61', '시험4': '72', '시험5': '98', '시험6': '84'}
{'이름': '조동욱', '학번': '20277510', '소속': '경제학과', '학년': '3', '시험1': '52', '시험2': '77', '시험3': '87', '시험4': '96', '시험5': '72', '시험6': '63'}
{'이름': '김승헌', '학번': '20317424', '소속': '경영학과', '학년': '3', '시험1': '83', '시험2': '90', '시험3': '93', '시험4': '71', '시험5': '89', '시험6': '92'}
{'이름': '정궁윤', '학번': '20299281', '소속': '생명과학과', '학년': '3', '시험1': '96', '시험2': '72', '시험3': '94', '시험4': '52', '시험5': '76', '시험6': '84'}
{'이름': '김민훈', '학번': '20317448', '소속': '의과학융합전공', '학년': '3', '시험1': '77', '시험2': '60', '시험3': '73', '시험4': '87', '시험5': '56', '시험6': '88'}
{'이름': '김동우', '학번': '20267372', '소속': '소프트웨어융합대학', 

## list에서 최솟값 제거

In [272]:
for i in scores:
    print(min(i))

46
55
57
52
71
52
56
47
55
43
50
58
59
56
55
45
61
55
50
72
54
57
60
73
53
52
41
44
51
57
53
59
67
60
65
54
50
50


In [276]:
for i in range(len(scores)):
    scores[i].remove(min(scores[i]))
scores

[[61, 69, 79, 57, 77],
 [83, 76, 62, 62, 64],
 [61, 61, 72, 98, 84],
 [77, 87, 96, 72, 63],
 [83, 90, 93, 89, 92],
 [96, 72, 94, 76, 84],
 [77, 60, 73, 87, 88],
 [58, 92, 61, 49, 70],
 [97, 82, 77, 58, 95],
 [67, 63, 90, 44, 85],
 [97, 84, 85, 54, 97],
 [88, 75, 65, 81, 61],
 [71, 99, 99, 87, 97],
 [100, 74, 57, 67, 63],
 [66, 93, 81, 99, 88],
 [97, 97, 60, 92, 91],
 [64, 71, 78, 82, 99],
 [77, 57, 65, 59, 74],
 [99, 60, 59, 75, 89],
 [90, 76, 90, 87, 91],
 [74, 55, 99, 100, 89],
 [83, 87, 85, 73, 65],
 [99, 64, 83, 77, 93],
 [96, 96, 78, 92, 99],
 [80, 93, 73, 58, 72],
 [54, 61, 65, 79, 69],
 [86, 91, 78, 70, 60],
 [68, 99, 68, 74, 94],
 [98, 87, 91, 65, 62],
 [97, 62, 62, 61, 72],
 [69, 60, 68, 74, 79],
 [93, 96, 99, 64, 88],
 [89, 81, 80, 100, 78],
 [89, 71, 96, 63, 89],
 [80, 89, 88, 66, 70],
 [78, 83, 100, 69, 56],
 [63, 91, 72, 59, 99],
 [100, 98, 79, 95, 70]]

In [315]:
scores = np.array(scores)
scores

array([[ 61,  69,  79,  57,  77],
       [ 83,  76,  62,  62,  64],
       [ 61,  61,  72,  98,  84],
       [ 77,  87,  96,  72,  63],
       [ 83,  90,  93,  89,  92],
       [ 96,  72,  94,  76,  84],
       [ 77,  60,  73,  87,  88],
       [ 58,  92,  61,  49,  70],
       [ 97,  82,  77,  58,  95],
       [ 67,  63,  90,  44,  85],
       [ 97,  84,  85,  54,  97],
       [ 88,  75,  65,  81,  61],
       [ 71,  99,  99,  87,  97],
       [100,  74,  57,  67,  63],
       [ 66,  93,  81,  99,  88],
       [ 97,  97,  60,  92,  91],
       [ 64,  71,  78,  82,  99],
       [ 77,  57,  65,  59,  74],
       [ 99,  60,  59,  75,  89],
       [ 90,  76,  90,  87,  91],
       [ 74,  55,  99, 100,  89],
       [ 83,  87,  85,  73,  65],
       [ 99,  64,  83,  77,  93],
       [ 96,  96,  78,  92,  99],
       [ 80,  93,  73,  58,  72],
       [ 54,  61,  65,  79,  69],
       [ 86,  91,  78,  70,  60],
       [ 68,  99,  68,  74,  94],
       [ 98,  87,  91,  65,  62],
       [ 97,  

In [323]:
scores = scores.mean(1).round(1)
scores

array([68.6, 69.4, 75.2, 79. , 89.4, 84.4, 77. , 66. , 81.8, 69.8, 83.4,
       74. , 90.6, 72.2, 85.4, 87.4, 78.8, 66.4, 76.4, 86.8, 83.4, 78.6,
       83.2, 92.2, 75.2, 65.6, 77. , 80.6, 80.6, 70.8, 70. , 88. , 85.6,
       81.6, 78.6, 77.2, 76.8, 88.4])

In [324]:
import csv
with open('fake_student_records.csv', mode='r', encoding='utf-8') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    scores = []
    exams = ('시험1', '시험2', '시험3', '시험4', '시험5', '시험6')
    for row in csv_reader:
        scores.append([int(row[e]) for e in exams])
        print(row)

{'이름': '조준혁', '학번': '20257329', '소속': '일본학과', '학년': '3', '시험1': '61', '시험2': '69', '시험3': '46', '시험4': '79', '시험5': '57', '시험6': '77'}
{'이름': '이중석', '학번': '20287434', '소속': '심리학과', '학년': '2', '시험1': '83', '시험2': '55', '시험3': '76', '시험4': '62', '시험5': '62', '시험6': '64'}
{'이름': '정은영', '학번': '20297500', '소속': '경제학과', '학년': '2', '시험1': '57', '시험2': '61', '시험3': '61', '시험4': '72', '시험5': '98', '시험6': '84'}
{'이름': '조동욱', '학번': '20277510', '소속': '경제학과', '학년': '3', '시험1': '52', '시험2': '77', '시험3': '87', '시험4': '96', '시험5': '72', '시험6': '63'}
{'이름': '김승헌', '학번': '20317424', '소속': '경영학과', '학년': '3', '시험1': '83', '시험2': '90', '시험3': '93', '시험4': '71', '시험5': '89', '시험6': '92'}
{'이름': '정궁윤', '학번': '20299281', '소속': '생명과학과', '학년': '3', '시험1': '96', '시험2': '72', '시험3': '94', '시험4': '52', '시험5': '76', '시험6': '84'}
{'이름': '김민훈', '학번': '20317448', '소속': '의과학융합전공', '학년': '3', '시험1': '77', '시험2': '60', '시험3': '73', '시험4': '87', '시험5': '56', '시험6': '88'}
{'이름': '김동우', '학번': '20267372', '소속': '소프트웨어융합대학', 